- name: pull apache 2.4.50 docker image
  community.docker.docker_image:
    name: httpd
    tag: 2.4.50-alpine
    source: pull

- name: ensure a container is running
  community.docker.docker_container:
    name: apache-server
    state: started
    image: "httpd:2.4.50-alpine"
    ports:
      - "80:80"
