- name: pull mysql docker image
  community.docker.docker_image:
    name: mysql/mysql-server
    source: pull

- name: ensure a container is running
  community.docker.docker_container:
    name: mysql-server
    state: started
    image: "mysql/mysql-server"
    pull: true
    ports:
      - "3306:3306"

- name: add port to security group
  amazon.aws.ec2_security_group:
    name: hostvars['localhost']['ec2_instance'][instances][0].security_groups[0].group_name
    region: us-east-1
    description: adding port 3306 to the created security port
    rules:
      - proto: tcp
        ports: 
        - 3306
        cidr_ip: 0.0.0.0/0
        rule_desc: enable port 3306
    # state: "present"