---
- name: create key pair using provided key_material
  amazon.aws.ec2_key:
    region: "{{ region }}"
    name: "{{ key_name }}"
    key_material: "{{ ssh_public_key }}"
    state: "{{ state }}"

- name: Create security group 
  amazon.aws.ec2_security_group:
    name: test-sg-fortirecon
    description: sg with rule descriptions
    vpc_id: "{{ vpc_id }}"
    region: us-east-1
    rules:
      - proto: tcp
        ports: 
        - 22
        - 3306
        - 21
        - 25
        - 80
        - 443
        - 8080
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all
    state: "{{ state }}"

- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "Target {{ item }}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}" 
    security_group: test-sg-fortirecon
    network:
      assign_public_ip: true
    image_id: "{{ ami_id }}"
    state: "{{ state }}"
  register: ec2_instance
  loop: 
    - 1
    - 2

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{ec2_instance.results[0].instances[0].public_ip_address}} port=22 delay=30 timeout=320 state=started

- name: Wait for the instances to boot by checking the ssh port
  wait_for: host={{ec2_instance.results[1].instances[0].public_ip_address}} port=22 delay=30 timeout=320 state=started

- name: Add a host local to your machines
  ansible.builtin.add_host:
    groups: server1
    name: "{{ec2_instance.results[0].instances[0].public_ip_address}}"

- name: Add a host local to your machines
  ansible.builtin.add_host:
    groups: server2
    name: "{{ec2_instance.results[1].instances[0].public_ip_address}}"