---
- name: Delete EC2 Instance
  hosts: localhost
  gather_facts: no
  vars:
    region: "us-east-1"  # Replace with your desired region
    instance_type: "t2.medium"  # Replace with your desired instance type
    ami_id: "ami-053b0d53c279acc90"  # Replace with the AMI ID of the desired image
    key_name: "ubuntu_key"  # Replace with the name of your existing EC2 key pair
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub')}} "
    vpc_id: "vpc-003943bfbe38c7574"
    state: "absent"

  tasks:
    - name: Delete key pair
      amazon.aws.ec2_key:
        region: "{{ region }}"
        name: "{{ key_name }}"
        key_material: "{{ ssh_public_key }}"
        state: "{{ state }}"

    - name: Delete instances
      amazon.aws.ec2_instance:
        name: "Target {{ item }}"
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}" 
        security_group: test-sg-fortirecon
        network:
          assign_public_ip: true
        image_id: "{{ ami_id }}"
        state: "{{ state }}"
      register: ec2_instance
      loop: 
        - 1
        - 2

    - name: Delete security group 
      amazon.aws.ec2_security_group:
        name: test-sg-fortirecon
        description: sg with rule descriptions
        vpc_id: "{{ vpc_id }}"
        region: us-east-1
        rules:
          - proto: tcp
            ports: 
            - 22
            cidr_ip: 0.0.0.0/0
        state: "{{ state }}"
