- name: pull nginx docker image
  community.docker.docker_image:
    name: nginx
    source: pull

- name: ensure a container is running
  community.docker.docker_container:
    name: nginx-server
    state: started
    image: "nginx"
    pull: true
    ports:
      - "80:80"

- name: add port to security group
  amazon.aws.ec2_security_group:
    name: hostvars['localhost']['ec2_instance'][instances][0].security_groups[0].group_name
    region: us-east-1
    description: adding port 80 to the created security port
    rules:
      - proto: tcp
        ports: 
        - 80
        cidr_ip: 0.0.0.0/0
        rule_desc: enable port 80
    state: "present"