- name: pull tomcat docker image
  community.docker.docker_image:
    name: tomcat
    source: pull

- name: ensure a container is running
  community.docker.docker_container:
    name: tomcat-server
    state: started
    image: "tomcat"
    ports:
      - "8080:8080"
