---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Add a Tomcat user
  ansible.builtin.user:
    name: tomcat
    state: present

- name: Create a Tomcat Group
  ansible.builtin.group:
    name: tomcat
    state: present

- name: Install JAVA
  ansible.builtin.apt:
    name: default-jdk
    state: present

- name: Create a Tomcat Directory
  ansible.builtin.file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes

- name: download & unarchive tomcat10 
  ansible.builtin.unarchive:
    src: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.21/bin/apache-tomcat-10.0.21.tar.gz
    dest: /opt/tomcat10
    remote_src: yes
    extra_opts: [--strip-components=1]
 
- name: Change ownership of tomcat directory
  ansible.builtin.file:
    path: /opt/tomcat10
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

#doubt here
# - name: Copy Tomcat service from local to remote
#   ansible.builtin.copy:
#     src: /etc/tomcat.service
#     dest: /etc/systemd/system/
#     mode: 0755
 
- name: Start and Enable Tomcat 10 on sever
  ansible.builtin.systemd:
    name: tomcat
    state: started
    daemon_reload: true